services:
  - type: web
    name: civic-issue-mini-project
    env: java
    buildCommand: mvn clean package
    startCommand: java -jar target/*.jar
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: SPRING_MAIL_USERNAME
        sync: false
      - key: SPRING_MAIL_PASSWORD
        sync: false